"""
fix_now.py — แก้ด่วน 3 ปัญหา
  1) nav.js   → syntax error (Unexpected identifier 'dark'/'none')
  2) search   → inject inline ที่ทำงานได้แน่นอน
  3) manifest → CORS error (บอก path ผิด)

python fix_now.py
"""
import os, sys, re, json, hashlib
from pathlib import Path

# ── ตั้งค่า ────────────────────────────────────────────────────
BASE_PATH = Path(r"D:\Projects\krubjang-site full")

# ── โหลด config ──────────────────────────────────────────────
sys.path.insert(0, str(BASE_PATH))
try:
    from config import (SITE_NAME, CATEGORIES, CATEGORY_PAGE_MAP,
                        หมวด_ไทย, CAT_COLORS)
    print(f"✅ โหลด config.py: {SITE_NAME}")
except Exception as e:
    print(f"⚠️  config.py: {e} — ใช้ค่าเริ่มต้น")
    SITE_NAME        = "ไอหมอก"
    CATEGORIES       = ['news','lifestyle','health','food','finance','technology','entertainment']
    CATEGORY_PAGE_MAP= {c: c+'.html' for c in CATEGORIES}
    หมวด_ไทย         = {"news":"ข่าวสาร","lifestyle":"ไลฟ์สไตล์","health":"สุขภาพ",
                        "food":"อาหาร","finance":"การเงิน","technology":"เทคโนโลยี",
                        "entertainment":"บันเทิง"}
    CAT_COLORS       = {}

# ══════════════════════════════════════════════════════════════
# 1) แก้ nav.js — เขียนใหม่ทั้งหมดให้ syntax ถูกต้อง 100%
# ══════════════════════════════════════════════════════════════
def fix_nav_js():
    print("\n[1/3] 🔧 แก้ nav.js ...")

    # สร้าง nav links จาก CATEGORIES
    def _link_line(c):
        href  = CATEGORY_PAGE_MAP.get(c, c + ".html")
        label = หมวด_ไทย.get(c, c)
        return '    { href: "' + href + '", label: "' + label + '" }'
    nav_links = "\n".join(_link_line(c) for c in CATEGORIES)

    # nav.js ใหม่ — ไม่มี template literal ที่อาจขัดแย้ง
    nav_js = r"""/* nav.js — auto-generated by fix_now.py */
(function () {
  var SITE_NAME = """ + json.dumps(SITE_NAME, ensure_ascii=False) + r""";
  var NAV_LINKS = [
""" + nav_links + r"""
  ];

  // ── ธีมสี ────────────────────────────────────────────────
  var PRIMARY   = "#1e40af";
  var DARK_BG   = "#0f172a";
  var NAV_BG    = "linear-gradient(135deg," + PRIMARY + "," + DARK_BG + ")";

  // ── Dark mode ────────────────────────────────────────────
  var DARK_KEY = "darkMode";
  function isDark() { try { return localStorage.getItem(DARK_KEY) === "1"; } catch(e){ return false; } }
  function applyDark(on) {
    document.documentElement.setAttribute("data-theme", on ? "dark" : "light");
    document.body.style.background = on ? "#0f172a" : "";
    document.body.style.color      = on ? "#e2e8f0" : "";
    var btn = document.getElementById("darkToggle");
    if (btn) btn.innerHTML = on ? "☀️" : "🌙";
    try { localStorage.setItem(DARK_KEY, on ? "1" : "0"); } catch(e){}
  }

  // ── สร้าง nav ────────────────────────────────────────────
  function buildNav() {
    var cur = location.pathname.split("/").pop() || "index.html";

    // wrapper
    var nav = document.querySelector("nav");
    if (!nav) { nav = document.createElement("nav"); document.body.insertBefore(nav, document.body.firstChild); }

    // styles
    if (!document.getElementById("navStyle")) {
      var st = document.createElement("style");
      st.id = "navStyle";
      st.textContent = [
        "nav{background:" + NAV_BG + ";padding:0 1rem;display:flex;align-items:center;",
        "flex-wrap:wrap;gap:.25rem;position:sticky;top:0;z-index:1000;",
        "box-shadow:0 2px 8px rgba(0,0,0,.25);}",
        "nav a{color:rgba(255,255,255,.85);text-decoration:none;padding:.55rem .75rem;",
        "border-radius:6px;font-size:.875rem;font-weight:500;transition:background .2s;}",
        "nav a:hover,nav a.active{background:rgba(255,255,255,.18);color:#fff;}",
        "nav .logo{font-size:1.1rem;font-weight:800;margin-right:.5rem;color:#fff;text-decoration:none;}",
        "nav .spacer{flex:1;}",
        "#darkToggle{background:transparent;border:1px solid rgba(255,255,255,.35);",
        "color:#fff;padding:.35rem .65rem;border-radius:6px;cursor:pointer;font-size:.9rem;}",
        "@media(max-width:600px){nav a{padding:.45rem .5rem;font-size:.78rem;}}"
      ].join("");
      document.head.appendChild(st);
    }

    // logo
    var logo = document.createElement("a");
    logo.href      = "index.html";
    logo.className = "logo";
    logo.textContent = SITE_NAME;
    nav.appendChild(logo);

    // links
    for (var i = 0; i < NAV_LINKS.length; i++) {
      var a = document.createElement("a");
      a.href = NAV_LINKS[i].href;
      a.textContent = NAV_LINKS[i].label;
      if (NAV_LINKS[i].href === cur) a.className = "active";
      nav.appendChild(a);
    }

    // spacer
    var sp = document.createElement("span");
    sp.className = "spacer";
    nav.appendChild(sp);

    // dark toggle
    var btn = document.createElement("button");
    btn.id        = "darkToggle";
    btn.innerHTML = isDark() ? "☀️" : "🌙";
    btn.setAttribute("aria-label", "สลับ dark mode");
    btn.onclick = function () { applyDark(!isDark()); };
    nav.appendChild(btn);

    // apply dark on load
    if (isDark()) applyDark(true);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", buildNav);
  } else {
    buildNav();
  }
})();
"""

    nav_path = BASE_PATH / "nav.js"
    nav_path.write_text(nav_js, encoding="utf-8")
    print(f"   ✅ เขียน nav.js ใหม่: {len(nav_js)} chars")


# ══════════════════════════════════════════════════════════════
# 2) สแกนบทความ → สร้าง search index
# ══════════════════════════════════════════════════════════════
_NON_ARTICLE = {
    "index.html","404.html","contact.html","sitemap.html","privacy.html",
    "style.css","nav.js","robots.txt","sitemap.xml","search-index.json",
    "news.html","lifestyle.html","health.html","food.html","finance.html",
    "technology.html","entertainment.html","ai.html","sport.html",
    "horoscope.html","entertainment.html","booking.html","gaming.html",
}

def _picsum(stem):
    seed = hashlib.md5(stem.encode()).hexdigest()[:8]
    return "https://picsum.photos/seed/" + seed + "/400/225"

def scan_articles():
    result = []
    for fp in sorted(BASE_PATH.glob("*.html")):
        if fp.name in _NON_ARTICLE:
            continue
        try:
            txt = fp.read_text(encoding="utf-8", errors="ignore")
            if "<html" in txt.lower() and len(txt) > 100:
                result.append(fp)
        except Exception:
            pass
    return result

def get_title(txt, fp):
    m = re.search(r'<h1[^>]*>(.*?)</h1>', txt, re.DOTALL | re.IGNORECASE)
    if m:
        return re.sub(r'<[^>]+>', '', m.group(1)).strip()
    m = re.search(r'<title[^>]*>(.*?)</title>', txt, re.DOTALL | re.IGNORECASE)
    if m:
        t = re.sub(r'<[^>]+>', '', m.group(1)).strip()
        return re.split(r'\s*[—|–|-]\s*', t)[0].strip()
    return fp.stem.replace("_", " ").replace("-", " ").title()

def get_img(txt, fp):
    m = re.search(r'<meta[^>]+property=["\']og:image["\'][^>]+content=["\']([^"\']+)["\']', txt, re.IGNORECASE)
    if m: return m.group(1).strip()
    m = re.search(r'<img[^>]+src=["\']([^"\']+)["\']', txt, re.IGNORECASE)
    if m:
        s = m.group(1).strip()
        if "icon" not in s.lower() and "logo" not in s.lower():
            return s
    return _picsum(fp.stem)

def get_cat(fp):
    stem = fp.stem
    cat  = stem.split("_")[0] if "_" in stem else stem
    return หมวด_ไทย.get(cat, cat)

def build_search_index():
    print("\n[2/3] 🔍 สร้าง search index ...")
    articles = scan_articles()
    entries  = []
    for fp in articles:
        try:
            txt = fp.read_text(encoding="utf-8", errors="ignore")
            entries.append({
                "t":   get_title(txt, fp),
                "u":   fp.name,
                "img": get_img(txt, fp),
                "cat": get_cat(fp),
            })
        except Exception as e:
            print(f"   ⚠️  skip {fp.name}: {e}")

    out = BASE_PATH / "search-index.json"
    out.write_text(json.dumps(entries, ensure_ascii=False, separators=(',',':')), encoding="utf-8")
    print(f"   ✅ search-index.json: {len(entries)} รายการ")
    return entries


# ══════════════════════════════════════════════════════════════
# 3) ฝัง search script ใน index.html (inline — ไม่ต้อง fetch)
# ══════════════════════════════════════════════════════════════
def inject_search(entries):
    print("\n[3/3] 🔎 ฝัง search ใน index.html ...")

    json_data = json.dumps(entries, ensure_ascii=False, separators=(',',':'))

    # search script — เขียนเป็น string ธรรมดา ไม่ใช้ f-string เพื่อหลีกเลี่ยง brace ขัดแย้ง
    search_script = (
        "<script id=\"searchScript\">\n"
        "(function(){\n"
        "  var DATA=" + json_data + ";\n"
        "  var inp=document.getElementById('search-input');\n"
        "  var box=document.getElementById('search-results');\n"
        "  if(!inp||!box){console.warn('search: ไม่พบ #search-input หรือ #search-results');return;}\n"
        "  box.style.cssText='position:absolute;top:115%;left:0;right:0;background:#fff;'\n"
        "    +'border-radius:14px;box-shadow:0 12px 32px rgba(0,0,0,.28);'\n"
        "    +'z-index:9999;overflow:hidden;max-height:380px;overflow-y:auto;display:none;';\n"
        "  var timer;\n"
        "  inp.addEventListener('input',function(){\n"
        "    clearTimeout(timer);\n"
        "    timer=setTimeout(function(){\n"
        "      var q=inp.value.trim().toLowerCase();\n"
        "      box.innerHTML='';\n"
        "      if(!q){box.style.display='none';return;}\n"
        "      var hits=DATA.filter(function(a){\n"
        "        return (a.t||'').toLowerCase().indexOf(q)>=0||(a.cat||'').toLowerCase().indexOf(q)>=0;\n"
        "      }).slice(0,10);\n"
        "      if(!hits.length){\n"
        "        box.innerHTML='<div style=\"padding:.75rem 1rem;color:#94a3b8;font-size:.85rem;\">ไม่พบบทความ</div>';\n"
        "        box.style.display='block';return;\n"
        "      }\n"
        "      hits.forEach(function(a){\n"
        "        var el=document.createElement('a');\n"
        "        el.href=a.u;\n"
        "        el.style.cssText='display:flex;gap:.6rem;align-items:center;padding:.6rem .9rem;'\n"
        "          +'border-bottom:1px solid #f1f5f9;text-decoration:none;color:#1e293b;';\n"
        "        el.onmouseover=function(){this.style.background='#f8fafc';};\n"
        "        el.onmouseout=function(){this.style.background='';};\n"
        "        var img=document.createElement('img');\n"
        "        img.src=a.img||'';\n"
        "        img.loading='lazy';\n"
        "        img.style.cssText='width:52px;height:38px;object-fit:cover;border-radius:5px;flex-shrink:0;';\n"
        "        img.onerror=function(){this.style.display='none';};\n"
        "        var info=document.createElement('div');\n"
        "        var title=document.createElement('div');\n"
        "        title.style.cssText='font-weight:600;font-size:.88rem;line-height:1.3;';\n"
        "        title.textContent=a.t||'';\n"
        "        var cat=document.createElement('div');\n"
        "        cat.style.cssText='font-size:.72rem;color:#94a3b8;margin-top:.1rem;';\n"
        "        cat.textContent=a.cat||'';\n"
        "        info.appendChild(title);\n"
        "        info.appendChild(cat);\n"
        "        el.appendChild(img);\n"
        "        el.appendChild(info);\n"
        "        box.appendChild(el);\n"
        "      });\n"
        "      box.style.display='block';\n"
        "    },180);\n"
        "  });\n"
        "  document.addEventListener('click',function(e){\n"
        "    if(!box.contains(e.target)&&e.target!==inp)box.style.display='none';\n"
        "  });\n"
        "  inp.addEventListener('keydown',function(e){\n"
        "    if(e.key==='Escape'){box.style.display='none';inp.value='';}\n"
        "  });\n"
        "})();\n"
        "</script>"
    )

    idx = BASE_PATH / "index.html"
    if not idx.exists():
        print("   ❌ ไม่พบ index.html")
        return

    html = idx.read_text(encoding="utf-8", errors="ignore")
    orig = html

    # ลบ searchScript เก่า (ถ้ามี)
    html = re.sub(r'<script id="searchScript">.*?</script>', '', html, flags=re.DOTALL)

    # ลบ search script แบบเก่าที่ใช้ fetch หรือ inline DATA เก่า
    html = re.sub(
        r'<script>\s*\(function\(\)\s*\{[\s\S]{0,200}?(?:search-index\.json|var DATA=\[)[\s\S]*?\}\)\(\);\s*</script>',
        '', html, flags=re.DOTALL
    )
    # ลบ try { fetch pattern
    html = re.sub(
        r'<script>\s*(?://[^\n]*)?\s*try\s*\{[\s\S]{0,100}?fetch\([\'"]search-index[\s\S]*?</script>',
        '', html, flags=re.DOTALL
    )

    # ฝัง script ใหม่ก่อน </body>
    if "</body>" in html:
        html = html.replace("</body>", search_script + "\n</body>", 1)
    else:
        html += "\n" + search_script

    if html != orig:
        idx.write_text(html, encoding="utf-8")
        print("   ✅ ฝัง search script ใน index.html สำเร็จ")
    else:
        print("   ℹ️  ไม่มีการเปลี่ยนแปลง (อาจมีอยู่แล้ว)")

    # ตรวจสอบว่า search-input และ search-results มีอยู่ใน HTML
    if 'id="search-input"' not in html and "id='search-input'" not in html:
        print("   ⚠️  ไม่พบ id=\"search-input\" ใน index.html!")
        print("      → รัน: python agent_fix_v5.py  เพื่อ rebuild index.html ก่อน")
    else:
        print("   ✅ พบ #search-input ใน index.html")

    if 'id="search-results"' not in html and "id='search-results'" not in html:
        print("   ⚠️  ไม่พบ id=\"search-results\" ใน index.html!")
    else:
        print("   ✅ พบ #search-results ใน index.html")


# ══════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════
def main():
    print("=" * 55)
    print("  🚑 Fix Now — แก้ nav.js + search (file:// safe)")
    print("=" * 55)
    print(f"  📁 {BASE_PATH}")

    if not BASE_PATH.exists():
        print(f"❌ ไม่พบโฟลเดอร์: {BASE_PATH}")
        return

    fix_nav_js()
    entries = build_search_index()
    inject_search(entries)

    print("\n" + "=" * 55)
    print("  ✅ เสร็จสิ้น! กด F5 รีเฟรชเบราว์เซอร์แล้วลองค้นหาดูครับ")
    print("  💡 ถ้า nav ยังไม่ขึ้น: Ctrl+Shift+R (hard refresh)")
    print("=" * 55)

if __name__ == "__main__":
    main()
