/* nav.js — auto-generated by agent_config.py  อย่าแก้ไฟล์นี้ตรงๆ */
(function() {
  const NAV_ITEMS = [
    { label: "อาหาร", href: "/food.html" },
    { label: "สุขภาพ", href: "/health.html" },
    { label: "ไลฟ์สไตล์", href: "/lifestyle.html" },
    { label: "ท่องเที่ยว", href: "/travel.html" },
    { label: "การเงิน", href: "/finance.html" },
    { label: "เทคโนโลยี", href: "/technology.html" },
    { label: "เกม", href: "/gaming.html" },
    { label: "ความงาม", href: "/beauty.html" },
    { label: "ผีสาง", href: "/ghost.html" },
    { label: "ดราม่า", href: "/drama.html" },
    { label: "แรงบันดาลใจ", href: "/inspirational.html" },
    { label: "ข่าว", href: "/news.html" },
    { label: "ธุรกิจ", href: "/business.html" },
    { label: "กีฬา", href: "/sport.html" },
    { label: "เคล็ดลับ", href: "/tips.html" },
  ];

  const SITE_NAME = "ครบจัง";
  const SITE_URL  = "https://krubjang.com";
  const STICKY    = true;

  function buildNav() {
    const links = NAV_ITEMS
      .map(n => `<a href="${SITE_URL}${n.href}">${n.label}</a>`)
      .join('');
    const nav = `
    <nav class="site-nav${STICKY ? ' sticky' : ''}">
      <div class="nav-inner">
        <a class="nav-logo" href="${SITE_URL}/">${SITE_NAME}</a>
        <button class="nav-toggle" aria-label="เมนู">☰</button>
        <div class="nav-links">${links}</div>
      </div>
    </nav>`;
    document.body.insertAdjacentHTML('afterbegin', nav);
    document.querySelector('.nav-toggle')?.addEventListener('click', () => {
      document.querySelector('.nav-links')?.classList.toggle('open');
    });
  }

  function buildFooter() {
    const social = ``;
    const footer = `
    <footer class="site-footer">
      <div class="footer-inner">
        <p class="footer-name">${SITE_NAME}</p>
        <p class="footer-desc">บทความไทยคุณภาพ ครบทุกหมวด</p>
        <div class="footer-social">${social}</div>
        <p class="footer-copy">© ${new Date().getFullYear()} ${SITE_NAME} · All rights reserved</p>
      </div>
    </footer>`;
    document.body.insertAdjacentHTML('beforeend', footer);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => { buildNav(); buildFooter(); });
  } else {
    buildNav(); buildFooter();
  }
})();
