/* nav.js — auto-generated by fix_now.py */
(function () {
  var SITE_NAME = "ไอหมอก";
  var NAV_LINKS = [
    { href: "news.html", label: "ข่าวสาร" }
    { href: "lifestyle.html", label: "ไลฟ์สไตล์" }
    { href: "health.html", label: "สุขภาพ" }
    { href: "food.html", label: "อาหาร" }
    { href: "finance.html", label: "การเงิน" }
    { href: "technology.html", label: "เทคโนโลยี" }
    { href: "entertainment.html", label: "บันเทิง" }
    { href: "travel.html", label: "travel" }
    { href: "horoscope.html", label: "ดูดวง" }
    { href: "ghost.html", label: "เรื่องลี้ลับ" }
    { href: "lottery.html", label: "หวย" }
    { href: "beauty.html", label: "ความงาม" }
    { href: "sport.html", label: "กีฬา" }
    { href: "education.html", label: "การศึกษา" }
    { href: "gaming.html", label: "เกมมิ่ง" }
    { href: "diy.html", label: "ดีไอวาย" }
    { href: "pet.html", label: "สัตว์เลี้ยง" }
    { href: "car.html", label: "รถยนต์" }
    { href: "law.html", label: "กฎหมาย" }
    { href: "business.html", label: "ธุรกิจ" }
    { href: "anime.html", label: "อนิเมะ" }
    { href: "movie.html", label: "ภาพยนตร์" }
    { href: "cooking.html", label: "ทำอาหาร" }
    { href: "story.html", label: "นิทาน/เรื่องเล่า" }
    { href: "comedy.html", label: "ตลก" }
    { href: "tips.html", label: "เคล็ดลับ" }
    { href: "story.html", label: "นิทานพื้นบ้าน" }
    { href: "story.html", label: "การ์ตูน" }
    { href: "entertainment.html", label: "ละคร/ดราม่า" }
    { href: "lifestyle.html", label: "สร้างแรงบันดาลใจ" }
  ];

  // ── ธีมสี ────────────────────────────────────────────────
  var PRIMARY   = "#1e40af";
  var DARK_BG   = "#0f172a";
  var NAV_BG    = "linear-gradient(135deg," + PRIMARY + "," + DARK_BG + ")";

  // ── Dark mode ────────────────────────────────────────────
  var DARK_KEY = "darkMode";
  function isDark() { try { return localStorage.getItem(DARK_KEY) === "1"; } catch(e){ return false; } }
  function applyDark(on) {
    document.documentElement.setAttribute("data-theme", on ? "dark" : "light");
    document.body.style.background = on ? "#0f172a" : "";
    document.body.style.color      = on ? "#e2e8f0" : "";
    var btn = document.getElementById("darkToggle");
    if (btn) btn.innerHTML = on ? "☀️" : "🌙";
    try { localStorage.setItem(DARK_KEY, on ? "1" : "0"); } catch(e){}
  }

  // ── สร้าง nav ────────────────────────────────────────────
  function buildNav() {
    var cur = location.pathname.split("/").pop() || "index.html";

    // wrapper
    var nav = document.querySelector("nav");
    if (!nav) { nav = document.createElement("nav"); document.body.insertBefore(nav, document.body.firstChild); }

    // styles
    if (!document.getElementById("navStyle")) {
      var st = document.createElement("style");
      st.id = "navStyle";
      st.textContent = [
        "nav{background:" + NAV_BG + ";padding:0 1rem;display:flex;align-items:center;",
        "flex-wrap:wrap;gap:.25rem;position:sticky;top:0;z-index:1000;",
        "box-shadow:0 2px 8px rgba(0,0,0,.25);}",
        "nav a{color:rgba(255,255,255,.85);text-decoration:none;padding:.55rem .75rem;",
        "border-radius:6px;font-size:.875rem;font-weight:500;transition:background .2s;}",
        "nav a:hover,nav a.active{background:rgba(255,255,255,.18);color:#fff;}",
        "nav .logo{font-size:1.1rem;font-weight:800;margin-right:.5rem;color:#fff;text-decoration:none;}",
        "nav .spacer{flex:1;}",
        "#darkToggle{background:transparent;border:1px solid rgba(255,255,255,.35);",
        "color:#fff;padding:.35rem .65rem;border-radius:6px;cursor:pointer;font-size:.9rem;}",
        "@media(max-width:600px){nav a{padding:.45rem .5rem;font-size:.78rem;}}"
      ].join("");
      document.head.appendChild(st);
    }

    // logo
    var logo = document.createElement("a");
    logo.href      = "index.html";
    logo.className = "logo";
    logo.textContent = SITE_NAME;
    nav.appendChild(logo);

    // links
    for (var i = 0; i < NAV_LINKS.length; i++) {
      var a = document.createElement("a");
      a.href = NAV_LINKS[i].href;
      a.textContent = NAV_LINKS[i].label;
      if (NAV_LINKS[i].href === cur) a.className = "active";
      nav.appendChild(a);
    }

    // spacer
    var sp = document.createElement("span");
    sp.className = "spacer";
    nav.appendChild(sp);

    // dark toggle
    var btn = document.createElement("button");
    btn.id        = "darkToggle";
    btn.innerHTML = isDark() ? "☀️" : "🌙";
    btn.setAttribute("aria-label", "สลับ dark mode");
    btn.onclick = function () { applyDark(!isDark()); };
    nav.appendChild(btn);

    // apply dark on load
    if (isDark()) applyDark(true);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", buildNav);
  } else {
    buildNav();
  }
})();
